version: "3.8"
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    environment:
      APP_ENV: ${APP_ENV}
    ports:
      - "3001:3000"
    volumes:
      - ./front:/app
      - /app/node_modules
    # depends_on:
    #   - back
